"""Agent architecture for KOTH AI."""

from .controller import ControllerError, ResearchController, ResearchLimits, ResearchRunSummary
from .gemini_adapter import (
    GeminiAdapterError,
    GeminiAPIError,
    GeminiClient,
    GeminiContextBuilder,
    GeminiProposal,
    GeminiProposalType,
    GeminiProposalValidationError,
    GeminiReasoningAdapter,
    GeminiResponseParsingError,
)
from .recon import (
    ArbitraryCommandError,
    BaseTool,
    ExecutionAdapter,
    GatewayExecutionAdapter,
    HttpProbeTool,
    MockExecutionAdapter,
    PolicyViolationError,
    ReconAgent,
    ReconError,
    ReconPlanner,
    TargetRegistry,
    ToolError,
    ToolRegistry,
    ToolValidationError,
    UnregisteredTargetError,
)

__all__ = [
    "ResearchController",
    "ResearchLimits",
    "ResearchRunSummary",
    "ControllerError",
    "GeminiReasoningAdapter",
    "GeminiProposal",
    "GeminiProposalType",
    "GeminiContextBuilder",
    "GeminiClient",
    "GeminiAdapterError",
    "GeminiAPIError",
    "GeminiResponseParsingError",
    "GeminiProposalValidationError",
    "ReconAgent",
    "ReconPlanner",
    "TargetRegistry",
    "ReconError",
    "UnregisteredTargetError",
    "BaseTool",
    "HttpProbeTool",
    "ToolRegistry",
    "ExecutionAdapter",
    "MockExecutionAdapter",
    "GatewayExecutionAdapter",
    "ToolError",
    "ToolValidationError",
    "ArbitraryCommandError",
    "PolicyViolationError",
]
